# Generated by Django 4.2.4 on 2023-09-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadmanagementapp', '0002_rename_district_branche_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='State',
            new_name='Statename',
        ),
    ]
