# Generated by Django 4.2.4 on 2023-09-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadmanagementapp', '0003_rename_state_district_statename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branche',
            old_name='state',
            new_name='Statename',
        ),
    ]
