# Generated by Django 4.2.4 on 2023-09-13 08:41

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('leadmanagementapp', '0004_rename_state_branche_statename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branche',
            name='District',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Statename', chained_model_field='Statename', on_delete=django.db.models.deletion.CASCADE, to='leadmanagementapp.district'),
        ),
    ]
