# Generated by Django 4.2.4 on 2023-09-21 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leadmanagementapp', '0005_alter_branche_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='available_trainers',
        ),
        migrations.RemoveField(
            model_name='course',
            name='chosen_trainers',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Trainers',
        ),
        migrations.AddField(
            model_name='course',
            name='Trainers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'trainerr', 'is_active': True}, related_name='UserTrainers', to=settings.AUTH_USER_MODEL),
        ),
    ]
