# Generated by Django 4.2.4 on 2023-09-13 07:43

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leadmanagementapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_source', models.CharField(choices=[('Option 1', 'Option 1'), ('Option 2', 'Option 2')], max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('verify_phone_number', models.BooleanField(default=False)),
                ('student_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('street', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50)),
                ('Alternative_email', models.EmailField(max_length=254)),
                ('Alternative_Address', models.CharField(max_length=200)),
                ('Mobile', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('Whatsapp', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=50)),
                ('rollno', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='student_photos/')),
                ('student_call_status', models.CharField(choices=[('Not Contacted', 'Not Contacted'), ('Contacted', 'Contacted')], max_length=20)),
                ('next_follow_up_date', models.DateField()),
                ('To_Staff', models.CharField(choices=[('Roshan', 'Roshan'), ('Mustafa', 'Mustafa')], max_length=50)),
                ('comments', models.TextField()),
                ('District', smart_selects.db_fields.ChainedForeignKey(chained_field='State', chained_model_field='State', on_delete=django.db.models.deletion.CASCADE, to='leadmanagementapp.district', verbose_name='District')),
            ],
        ),
    ]
