# Generated by Django 4.2.4 on 2023-09-15 06:25

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('leadmanagementapp', '0005_alter_branche_district'),
        ('Students', '0003_alter_student_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='statename',
            new_name='Statename',
        ),
        migrations.AlterField(
            model_name='student',
            name='District',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='Statename', chained_model_field='Statename', on_delete=django.db.models.deletion.CASCADE, to='leadmanagementapp.district'),
        ),
    ]
